### ISSUE TITLE
Querying a list temporally renders the component with an empty value

### ISSUE THREAD

**Issue by iquabius** [PabloSzx/new_gqless#4]
I'm trying this lib out with Expo/React Native, and I'm noticing something weird.

During the first render, before the data is fetched, the list has only one item with all properties `undefined`:

```ts
const query = useQuery()
const courses = query.courses()
// first render:
// courses.length = 1
// courses[0] = Object {}
// Object.keys(Courses[0]) = Array ["__typename", "id", "title"]
// Courses[0].id =  undefined
```

I noticed this because I'm using the `id` field as key when iterating over the list. And I keep getting the React warning: `Each child in a list should have a unique "key" prop.`

The only way I found to avoid this is by guarding the component render:

```ts
if (courses[0].id === undefined) {
  return <Text>Loading...</Text>
}
```

My expectation is that suspense would prevent rendering the component before the data arrives. Am I missing something? Are my expectations wrong?

**Comment by iquabius** [comment]
I wanted to reproduce it in one of the react examples but I got a build error after cloning the repo on linux:

```sh
packages/gqless prepare$ build gqless
│ file:///home/iqb/Code/Sogni/sandbox/new_gqless/internal/build-utils/src/config.js:7
│ import { getBabelOutputPlugin } from '@rollup/plugin-babel';
│          ^^^^^^^^^^^^^^^^^^^^
│ SyntaxError: The requested module '@rollup/plugin-babel' is expected to be of type CommonJS, which d
│ For example:
│ import pkg from '@rollup/plugin-babel';
│ const { getBabelOutputPlugin } = pkg;
│     at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
│     at async ModuleJob.run (internal/modules/esm/module_job.js:135:5)
│     at async Loader.import (internal/modules/esm/loader.js:178:24)
└─ Failed in 122ms
 ERROR  Command failed with exit code 1.
```

**Comment by PabloSzx** [comment]
> I wanted to reproduce it in one of the react examples but I got a build error after cloning the repo on linux:
> 
> ```shell
> packages/gqless prepare$ build gqless
> │ file:///home/iqb/Code/Sogni/sandbox/new_gqless/internal/build-utils/src/config.js:7
> │ import { getBabelOutputPlugin } from '@rollup/plugin-babel';
> │          ^^^^^^^^^^^^^^^^^^^^
> │ SyntaxError: The requested module '@rollup/plugin-babel' is expected to be of type CommonJS, which d
> │ For example:
> │ import pkg from '@rollup/plugin-babel';
> │ const { getBabelOutputPlugin } = pkg;
> │     at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
> │     at async ModuleJob.run (internal/modules/esm/module_job.js:135:5)
> │     at async Loader.import (internal/modules/esm/loader.js:178:24)
> └─ Failed in 122ms
>  ERROR  Command failed with exit code 1.
> ```

what version of Node.js are you using?

**Comment by iquabius** [comment]
> what version of Node.js are you using?

```sh
➜ node --version
v14.4.0
```

**Comment by PabloSzx** [comment]
> > what version of Node.js are you using?
> 
> ```shell
> ➜ node --version
> v14.4.0
> ```

I just pushed the possible fix in master, try now please

PS: It's weird it doesn't work, I'm testing for node 12, 14 and 15 in github actions 🙄

**Comment by iquabius** [comment]
Now the error is a little different:

```sh
└─ Done in 1.1s
packages/gqless prepare$ build gqless
│ file:///home/iqb/Code/Sogni/sandbox/new_gqless/internal/build-utils/src/config.js:27
│ const babelPlugin = getBabelOutputPlugin({
│                     ^
│ TypeError: getBabelOutputPlugin is not a function
│     at file:///home/iqb/Code/Sogni/sandbox/new_gqless/internal/build-utils/src/config.js:27:21
│     at ModuleJob.run (internal/modules/esm/module_job.js:138:23)
│     at async Loader.import (internal/modules/esm/loader.js:178:24)
└─ Failed in 757ms
 ERROR  Command failed with exit code 1.
```

**Comment by PabloSzx** [comment]
> Now the error is a little different:
> 
> ```shell
> └─ Done in 1.1s
> packages/gqless prepare$ build gqless
> │ file:///home/iqb/Code/Sogni/sandbox/new_gqless/internal/build-utils/src/config.js:27
> │ const babelPlugin = getBabelOutputPlugin({
> │                     ^
> │ TypeError: getBabelOutputPlugin is not a function
> │     at file:///home/iqb/Code/Sogni/sandbox/new_gqless/internal/build-utils/src/config.js:27:21
> │     at ModuleJob.run (internal/modules/esm/module_job.js:138:23)
> │     at async Loader.import (internal/modules/esm/loader.js:178:24)
> └─ Failed in 757ms
>  ERROR  Command failed with exit code 1.
> ```

can you check in your node_modules what version of @rollup/plugin-babel is it installing?

**Comment by iquabius** [comment]
```sh
➜ head node_modules/@rollup/plugin-babel/package.json
{
  "name": "@rollup/plugin-babel",
  "version": "5.3.0",
  "publishConfig": {
    "access": "public"
  },
  "description": "Seamless integration between Rollup and Babel.",
  "license": "MIT",
  "repository": "rollup/plugins",
  "author": "Rich Harris",
```

**Comment by PabloSzx** [comment]
@iquabius I just pushed the changes replacing all the import with "createRequire", which should work since v12.2.0+

**Comment by iquabius** [comment]
I tried using Node 14.14.0 and it worked before pulling your last changes.

And with the last changes it worked on the previous version 14.4.0

**Comment by PabloSzx** [comment]
it definitely has to do with some Node.js regression with ESM support, but with createRequire it shouldn't have any issues

**Comment by PabloSzx** [comment]
> My expectation is that suspense would prevent rendering the component before the data arrives. Am I missing something? Are my expectations wrong?

now, addressing this specific issue, when using useQuery we can't intercept the commit phase with hooks right away, and that implies an extra render before suspending, which means that "prevent rendering" with hooks is not possible as we might like, but for the same reason there is another function called "graphql", which is a HOC (higher order component) that does allow suspending before the rendering phase.

In practice, using the hook is way easier and better overall, and with some logic like we discussed in discord, there is no problem using it, but if you want to prevent the render phase, your only choice is to use the "graphql" HOC.

This trade-off will be talked in the docs.

**Comment by PabloSzx** [comment]
@iquabius I talked about it in the docs [(https://reactjs.org/docs/higher-order-components.html)](https://reactjs.org/docs/higher-order-components.html), please tell me if you think it's alright

**Comment by iquabius** [comment]
Thanks! I'll take a look.
